function A = getnearquad(npatches,norders,ixyzs, ...
          iptype,npts,srccoefs,srcvals,targinfo,ipatch_id, uvs_targ, eps,...
            iquadtype,nnz, ...
          row_ptr,col_ind,iquad,rfac0,dpars,zpars,nquad,type)
    [n12,npts] = size(srcvals);
    [n9,~] = size(srccoefs);
    npp1 = npatches+1;

    [targs] = extract_targ_array(targinfo);
    [ndtarg,ntarg] = size(targs);
    ntargp1 = ntarg+1;
    nnzp1 = nnz+1;
    ndz = length(zpars);

    A = zeros(1,nquad,'like',1i);

    if strcmp(type, 'v2v') || strcmp(type, 'v2bd') || strcmp(type, 'dir')
            mex_id_ = 'getnearquad_flex2d_dir(i int64_t[x], i int64_t[x], i int64_t[x], i int64_t[x], i int64_t[x], i double[xx], i double[xx], i int64_t[x], i int64_t[x], i double[xx], i int64_t[x], i double[xx], i double[x], i dcomplex[x], i int64_t[x], i int64_t[x], i int64_t[x], i int64_t[x], i int64_t[x], i double[x], i int64_t[x], io dcomplex[x])';
[A] = kern_routs(mex_id_, npatches, norders, ixyzs, iptype, npts, srccoefs, srcvals, ndtarg, ntarg, targs, ipatch_id, uvs_targ, eps, zpars, iquadtype, nnz, row_ptr, col_ind, iquad, rfac0, nquad, A, 1, npatches, npp1, npatches, 1, n9, npts, n12, npts, 1, 1, ndtarg, ntarg, ntarg, 2, ntarg, 1, 2, 1, 1, ntargp1, nnz, nnzp1, 1, 1, nquad);
    elseif strcmp(type, 'v2bn') || strcmp(type, 'neu')
            mex_id_ = 'getnearquad_flex2d_neu(i int64_t[x], i int64_t[x], i int64_t[x], i int64_t[x], i int64_t[x], i double[xx], i double[xx], i int64_t[x], i int64_t[x], i double[xx], i int64_t[x], i double[xx], i double[x], i dcomplex[x], i int64_t[x], i int64_t[x], i int64_t[x], i int64_t[x], i int64_t[x], i double[x], i int64_t[x], io dcomplex[x])';
[A] = kern_routs(mex_id_, npatches, norders, ixyzs, iptype, npts, srccoefs, srcvals, ndtarg, ntarg, targs, ipatch_id, uvs_targ, eps, zpars, iquadtype, nnz, row_ptr, col_ind, iquad, rfac0, nquad, A, 1, npatches, npp1, npatches, 1, n9, npts, n12, npts, 1, 1, ndtarg, ntarg, ntarg, 2, ntarg, 1, 2, 1, 1, ntargp1, nnz, nnzp1, 1, 1, nquad);
    elseif strcmp(type, 'v2bs') || strcmp(type, 'supp2') || strcmp(type, 'free1')
            mex_id_ = 'getnearquad_flex2d_supp2(i int64_t[x], i int64_t[x], i int64_t[x], i int64_t[x], i int64_t[x], i double[xx], i double[xx], i int64_t[x], i int64_t[x], i double[xx], i int64_t[x], i double[xx], i double[x], i double[x], i dcomplex[x], i int64_t[x], i int64_t[x], i int64_t[x], i int64_t[x], i int64_t[x], i double[x], i int64_t[x], io dcomplex[x])';
[A] = kern_routs(mex_id_, npatches, norders, ixyzs, iptype, npts, srccoefs, srcvals, ndtarg, ntarg, targs, ipatch_id, uvs_targ, eps, dpars, zpars, iquadtype, nnz, row_ptr, col_ind, iquad, rfac0, nquad, A, 1, npatches, npp1, npatches, 1, n9, npts, n12, npts, 1, 1, ndtarg, ntarg, ntarg, 2, ntarg, 1, 1, 2, 1, 1, ntargp1, nnz, nnzp1, 1, 1, nquad);
    elseif strcmp(type, 'v2bf') || strcmp(type, 'free2')
            mex_id_ = 'getnearquad_flex2d_free2(i int64_t[x], i int64_t[x], i int64_t[x], i int64_t[x], i int64_t[x], i double[xx], i double[xx], i int64_t[x], i int64_t[x], i double[xx], i int64_t[x], i double[xx], i double[x], i double[x], i dcomplex[x], i int64_t[x], i int64_t[x], i int64_t[x], i int64_t[x], i int64_t[x], i double[x], i int64_t[x], io dcomplex[x])';
[A] = kern_routs(mex_id_, npatches, norders, ixyzs, iptype, npts, srccoefs, srcvals, ndtarg, ntarg, targs, ipatch_id, uvs_targ, eps, dpars, zpars, iquadtype, nnz, row_ptr, col_ind, iquad, rfac0, nquad, A, 1, npatches, npp1, npatches, 1, n9, npts, n12, npts, 1, 1, ndtarg, ntarg, ntarg, 2, ntarg, 1, 1, 2, 1, 1, ntargp1, nnz, nnzp1, 1, 1, nquad);
    elseif strcmp(type, 'free2_var')
            mex_id_ = 'getnearquad_flex2d_free2_var(i int64_t[x], i int64_t[x], i int64_t[x], i int64_t[x], i int64_t[x], i double[xx], i double[xx], i int64_t[x], i int64_t[x], i double[xx], i int64_t[x], i double[xx], i double[x], i double[x], i dcomplex[x], i int64_t[x], i int64_t[x], i int64_t[x], i int64_t[x], i int64_t[x], i double[x], i int64_t[x], io dcomplex[x])';
[A] = kern_routs(mex_id_, npatches, norders, ixyzs, iptype, npts, srccoefs, srcvals, ndtarg, ntarg, targs, ipatch_id, uvs_targ, eps, dpars, zpars, iquadtype, nnz, row_ptr, col_ind, iquad, rfac0, nquad, A, 1, npatches, npp1, npatches, 1, n9, npts, n12, npts, 1, 1, ndtarg, ntarg, ntarg, 2, ntarg, 1, 1, 2, 1, 1, ntargp1, nnz, nnzp1, 1, 1, nquad);
    elseif strcmp(type,'free')
        A1 = flex2d.getnearquad(npatches,norders,ixyzs, ...
          iptype,npts,srccoefs,srcvals,targinfo,ipatch_id, uvs_targ, eps,...
            iquadtype,nnz, ...
          row_ptr,col_ind,iquad,rfac0,dpars,zpars,nquad,'free1');
        A2 = flex2d.getnearquad(npatches,norders,ixyzs, ...
          iptype,npts,srccoefs,srcvals,targinfo,ipatch_id, uvs_targ, eps,...
            iquadtype,nnz, ...
          row_ptr,col_ind,iquad,rfac0,dpars,zpars,nquad,'free2');
        A = [A1,A2];
    elseif strcmp(type,'free_var')
        A1 = flex2d.getnearquad(npatches,norders,ixyzs, ...
          iptype,npts,srccoefs,srcvals,targinfo,ipatch_id, uvs_targ, eps,...
            iquadtype,nnz, ...
          row_ptr,col_ind,iquad,rfac0,dpars,zpars,nquad,'free1');
        A2 = flex2d.getnearquad(npatches,norders,ixyzs, ...
          iptype,npts,srccoefs,srcvals,targinfo,ipatch_id, uvs_targ, eps,...
            iquadtype,nnz, ...
          row_ptr,col_ind,iquad,rfac0,dpars,zpars,nquad,'free2_var');
        A = [A1,A2];
    elseif strcmp(type,'supported')
        A1 = flex2d.getnearquad(npatches,norders,ixyzs, ...
          iptype,npts,srccoefs,srcvals,targinfo,ipatch_id, uvs_targ, eps,...
            iquadtype,nnz, ...
          row_ptr,col_ind,iquad,rfac0,dpars,zpars,nquad,'dir');
        A2 = flex2d.getnearquad(npatches,norders,ixyzs, ...
          iptype,npts,srccoefs,srcvals,targinfo,ipatch_id, uvs_targ, eps,...
            iquadtype,nnz, ...
          row_ptr,col_ind,iquad,rfac0,dpars,zpars,nquad,'supp2');
        A = [A1,A2];
    elseif strcmp(type,'clamped')
        A1 = flex2d.getnearquad(npatches,norders,ixyzs, ...
          iptype,npts,srccoefs,srcvals,targinfo,ipatch_id, uvs_targ, eps,...
            iquadtype,nnz, ...
          row_ptr,col_ind,iquad,rfac0,dpars,zpars,nquad,'dir');
        A2 = flex2d.getnearquad(npatches,norders,ixyzs, ...
          iptype,npts,srccoefs,srcvals,targinfo,ipatch_id, uvs_targ, eps,...
            iquadtype,nnz, ...
          row_ptr,col_ind,iquad,rfac0,dpars,zpars,nquad,'neu');
        A = [A1,A2];
    end

end
%
%
